unique_ids:
  forms: {form_main.form_sub1_input: 7MYSTEFMWLERSXWHMZVPLOZHKNV2AAJO, form_main.form_sub2_pnl_mth_rpt.pnl_mth_rpt_template: OUTTZAPFSS7IJQ6B6S7IQ5RBBM6UKNAW,
    form_main: TNMWRJE7DZEPVMK6Y7CTQHGKSVRCWLHW, form_main.form_sub1_dashb: YCOTFVKCETZYRXPD2PMBQDI4VRTGFGTX,
    form_main.form_lv2_tranx_list.tranx_list_template: AL4Z2J5EBQ7HJ43FMVZTJDGC5EDPLC7R,
    form_main.form_sub2_pnl_mth_rpt: RXSUKLOJQBDAVUQEX2WJTJ7ASDCEMEHA, form_main.form_testa: I4UQL5D742KHJ2RDJH22CP7RC7QSJ56P,
    form_main.form_sub1_settings: 5G7DFUL2LGGTGEOA7RETQ2OGQAZDZ7A7, form_main.form_sub1_input.input_template: RATFOYIZP6VUKZC3UPCLVGOSPW6MLNYC,
    form_main.form_sub2_tranx_report.tranx_rpt_template: 7SERJS6BWF3NCCVG4Z5QDB7QCAK6VTMS,
    form_main.form_testb: GYQQVHBPYST36H775CH4WEQ5PNDAIYWI, form_main.form_lv2_tranx_list: YRMUCP7QSPKGEVKGLM36RIZSHRVDDC7H,
    form_main.form_lv2_search_panel: FQP5E6OBNXXRA6NQJU65QDQRFAMBPLTZ, form_main.form_testc: QAA6QNVH7ZYUIV7UFYET7ZJNCHOIGE3Q,
    form_main.form_sub2_tranx_report: MRI3WC7LWBPT5DWPJICJAYXMAI4K7DR2}
  modules: {global_var: VE45ZBNU3EG37QJDLRLJDZU34MMRFSY3}
  server_modules: {ServerModule_Input: X45I2HKCTR4L4RTO5ZJPFZDW2YWARRQR, ServerModule_Reports: F5WT3XNIK7VFZ6ANI7HHS4N7VHWLWKRD}
  assets: {standard-page.html: D5YEDRDJMYZPOK73N7L4R7WKW5PNRV5I, theme.css: LKAL32R6ENKSBIEKBOLZNABHFXK7Z36N}
