unique_ids:
  forms:
    Debug.form_poc3: QAA6QNVH7ZYUIV7UFYET7ZJNCHOIGE3Q
    Input.ExpenseInputForm: SRFHXWORWERSKLPNHEKXYQDNXXI6KVAD
    Input.StockInputForm: 7MYSTEFMWLERSXWHMZVPLOZHKNV2AAJO
    Debug.form_poc1: KYO5FGE65NN57JIZOC5GCH4ADCZHQIY2
    Debug.form_poc2: GYQQVHBPYST36H775CH4WEQ5PNDAIYWI
    Report.form_lv2_exp_list.exp_list_template: RWAT53FDTVD4Q55MXXCE42TFTRYLHUEO
    Report.TransactionReportForm.TransactionReportRPTemplate: 6K6GMJTMVMSL52CSQJ3CUTCSGCAZNEFP
    Report.TransactionReportForm: RIRZNO5HLZG3BBXUQPIAHECUW4RKHDWF
    Report.DashboardForm: YCOTFVKCETZYRXPD2PMBQDI4VRTGFGTX
    Report.ReportSearchPanelFrom: N5B5BWMYWFAPKOSC5WVBY77HNLJZKI2K
    Debug.form_poc_main: I4UQL5D742KHJ2RDJH22CP7RC7QSJ56P
    Input.StockInputForm.StockInputRPTemplate: RATFOYIZP6VUKZC3UPCLVGOSPW6MLNYC
    Report.PnLReportForm.PnLReportRPTemplate: OUTTZAPFSS7IJQ6B6S7IQ5RBBM6UKNAW
    Obsolete.form_sub2_tranx_report: MRI3WC7LWBPT5DWPJICJAYXMAI4K7DR2
    Obsolete.form_sub2_tranx_report.tranx_rpt_template: 7SERJS6BWF3NCCVG4Z5QDB7QCAK6VTMS
    Report.form_lv2_exp_list: SVBUOIX7NY24L72NVIWCMW2E2G6EHBY2
    MainForm: TNMWRJE7DZEPVMK6Y7CTQHGKSVRCWLHW
    Review.form_lv2_review: WWHVQCGKTW67MKBTLMMZZ4NG54XSGW54
    Admin.SettingForm: 5G7DFUL2LGGTGEOA7RETQ2OGQAZDZ7A7
    Debug.form_poc2.test_template: I7VGCOHGIK32TFWPVUUSRN2KTIJVLDLX
    Report.PnLReportForm: RXSUKLOJQBDAVUQEX2WJTJ7ASDCEMEHA
  modules:
    Review: 6NLYLGXG7GLS54UWYCWESF5UROG7VEWK
    Report: OIVNGKW42U6ALEZG7Y6DQDQP6EAAB2LG
    Input: IKOMETFPBHT3EUYN44QPTTVOWMQHISL5
    Obsolete: Y4364HZE4MUURV7CP7GF6WVIE6BHRZ6K
    Debug: O2JWN6XWAZ54VIJ6WY7RDXXNZB2HMQSU
    validation: D2POMW5PCGKFZOK3G6L7RVS5GCXYOJRC
    Global: FHR7AUB3TOZEXS524FAI5C27TWW3V3IE
    Admin: JKDAEBJOUEYGTKZG3EQHTXMTMKUF3NWB
  server_modules:
    AdminProcess: '167960502352321275840385.37744'
    DataObject.FinObject: '1678927047037156167445546.5809'
    System.SysInternalModule: IA5VHKS4CE5NZB5NHAL6VHVR7LZKARDT
    DataObject: '1679603158086613851626628.8792'
    InvestmentProcess.ReportingModule: F5WT3XNIK7VFZ6ANI7HHS4N7VHWLWKRD
    mod_logon: YUF4QN4ZJUCVGKNYBAGBYOFY3LILSLNV
    AdminProcess.ConfigModule: 7JGJZHJ343YHLDTREZYBRYRCBODPM7HV
    InvestmentProcess.InputModule: X45I2HKCTR4L4RTO5ZJPFZDW2YWARRQR
    anvildb_mod_input: '1678930162396348734424009.2063'
    System: '1679606597632634541723147.0587'
    InvestmentProcess: '1679603582677151295880728.9948'
  assets:
    new-homepage.html: J5QGC4NFVJRLMUASFBM37UTFKGDKAKR6
    standard-page.html: D5YEDRDJMYZPOK73N7L4R7WKW5PNRV5I
    theme.css: LKAL32R6ENKSBIEKBOLZNABHFXK7Z36N
