unique_ids:
  forms:
    Report.form_lv2_search_panel: N5B5BWMYWFAPKOSC5WVBY77HNLJZKI2K
    Debug.form_poc3: QAA6QNVH7ZYUIV7UFYET7ZJNCHOIGE3Q
    Debug.form_poc1: KYO5FGE65NN57JIZOC5GCH4ADCZHQIY2
    Report.form_lv2_tranx_list: RIRZNO5HLZG3BBXUQPIAHECUW4RKHDWF
    Debug.form_poc2: GYQQVHBPYST36H775CH4WEQ5PNDAIYWI
    form_main: TNMWRJE7DZEPVMK6Y7CTQHGKSVRCWLHW
    Report.form_lv1_dashb: YCOTFVKCETZYRXPD2PMBQDI4VRTGFGTX
    Debug.form_poc_main: I4UQL5D742KHJ2RDJH22CP7RC7QSJ56P
    Report.form_lv2_pnl_report.pnl_report_template: OUTTZAPFSS7IJQ6B6S7IQ5RBBM6UKNAW
    Obsolete.form_sub2_tranx_report: MRI3WC7LWBPT5DWPJICJAYXMAI4K7DR2
    Report.form_lv2_tranx_list.tranx_list_template: 6K6GMJTMVMSL52CSQJ3CUTCSGCAZNEFP
    Input.form_lv1_input: 7MYSTEFMWLERSXWHMZVPLOZHKNV2AAJO
    Obsolete.form_sub2_tranx_report.tranx_rpt_template: 7SERJS6BWF3NCCVG4Z5QDB7QCAK6VTMS
    Report.form_lv2_pnl_report: RXSUKLOJQBDAVUQEX2WJTJ7ASDCEMEHA
    Review.form_lv2_review: WWHVQCGKTW67MKBTLMMZZ4NG54XSGW54
    Input.form_lv1_input.input_template: RATFOYIZP6VUKZC3UPCLVGOSPW6MLNYC
    Admin.form_lv1_settings: 5G7DFUL2LGGTGEOA7RETQ2OGQAZDZ7A7
    Debug.form_poc2.test_template: I7VGCOHGIK32TFWPVUUSRN2KTIJVLDLX
  modules:
    Review: 6NLYLGXG7GLS54UWYCWESF5UROG7VEWK
    Report: OIVNGKW42U6ALEZG7Y6DQDQP6EAAB2LG
    Input: IKOMETFPBHT3EUYN44QPTTVOWMQHISL5
    Obsolete: Y4364HZE4MUURV7CP7GF6WVIE6BHRZ6K
    Debug: O2JWN6XWAZ54VIJ6WY7RDXXNZB2HMQSU
    global_var: FHR7AUB3TOZEXS524FAI5C27TWW3V3IE
    validation: D2POMW5PCGKFZOK3G6L7RVS5GCXYOJRC
    Admin: JKDAEBJOUEYGTKZG3EQHTXMTMKUF3NWB
  server_modules:
    mod_debug: IA5VHKS4CE5NZB5NHAL6VHVR7LZKARDT
    mod_input: X45I2HKCTR4L4RTO5ZJPFZDW2YWARRQR
    mod_report: F5WT3XNIK7VFZ6ANI7HHS4N7VHWLWKRD
    mod_setting: 7JGJZHJ343YHLDTREZYBRYRCBODPM7HV
    mod_logon: JI3V4C446QH2WVQ2XMYZIZ4GWOIJXODW
  assets:
    standard-page.html: D5YEDRDJMYZPOK73N7L4R7WKW5PNRV5I
    theme.css: LKAL32R6ENKSBIEKBOLZNABHFXK7Z36N
