unique_ids:
  forms: {form_main: TNMWRJE7DZEPVMK6Y7CTQHGKSVRCWLHW}
  modules: {}
  server_modules: {}
  assets: {standard-page.html: D5YEDRDJMYZPOK73N7L4R7WKW5PNRV5I, theme.css: LKAL32R6ENKSBIEKBOLZNABHFXK7Z36N}
