unique_ids:
  forms: {form_main.form_lv1_settings: 5G7DFUL2LGGTGEOA7RETQ2OGQAZDZ7A7, form_main.form_poc_main: I4UQL5D742KHJ2RDJH22CP7RC7QSJ56P,
    form_main.form_lv1_input.input_template: RATFOYIZP6VUKZC3UPCLVGOSPW6MLNYC, form_main: TNMWRJE7DZEPVMK6Y7CTQHGKSVRCWLHW,
    form_main.form_lv1_input: 7MYSTEFMWLERSXWHMZVPLOZHKNV2AAJO, form_main.form_poc2.test_template: I7VGCOHGIK32TFWPVUUSRN2KTIJVLDLX,
    form_main.form_lv2_tranx_list.tranx_list_template: 6K6GMJTMVMSL52CSQJ3CUTCSGCAZNEFP,
    form_main.form_poc2: GYQQVHBPYST36H775CH4WEQ5PNDAIYWI, form_main.form_poc1: KYO5FGE65NN57JIZOC5GCH4ADCZHQIY2,
    form_main.form_lv2_pnl_report.pnl_report_template: OUTTZAPFSS7IJQ6B6S7IQ5RBBM6UKNAW,
    form_main.form_poc3: QAA6QNVH7ZYUIV7UFYET7ZJNCHOIGE3Q, form_main.form_lv2_pnl_report: RXSUKLOJQBDAVUQEX2WJTJ7ASDCEMEHA,
    form_main.form_sub2_tranx_report.tranx_rpt_template: 7SERJS6BWF3NCCVG4Z5QDB7QCAK6VTMS,
    form_main.form_lv2_tranx_list: RIRZNO5HLZG3BBXUQPIAHECUW4RKHDWF, form_main.form_lv1_dashb: YCOTFVKCETZYRXPD2PMBQDI4VRTGFGTX,
    form_main.form_lv2_search_panel: N5B5BWMYWFAPKOSC5WVBY77HNLJZKI2K, form_main.form_sub2_tranx_report: MRI3WC7LWBPT5DWPJICJAYXMAI4K7DR2}
  modules: {global_var: FHR7AUB3TOZEXS524FAI5C27TWW3V3IE}
  server_modules: {mod_debug: XRYODBLVWI24MTBVLWHNSRNSSYMHIIBW, mod_input: X45I2HKCTR4L4RTO5ZJPFZDW2YWARRQR,
    mod_report: F5WT3XNIK7VFZ6ANI7HHS4N7VHWLWKRD}
  assets: {standard-page.html: D5YEDRDJMYZPOK73N7L4R7WKW5PNRV5I, theme.css: LKAL32R6ENKSBIEKBOLZNABHFXK7Z36N}
