import anvil.secrets
import anvil.users
import anvil.tables as tables
import anvil.tables.query as q
from anvil.tables import app_tables
import anvil.server
import psycopg2
import psycopg2.extras

# This is a server module. It runs on the Anvil server,
# rather than in the user's browser.

@anvil.server.callable
# Get user logon name
def get_current_username():
    userid = anvil.users.get_user().get_id()
    row = (app_tables.users.get_by_id(userid))['email']
    return row if row is not None else None

@anvil.server.callable
# Get user id (generated by Python)
def get_current_userid():
    userid = anvil.users.get_user().get_id()
    return userid[userid.find(",")+1:len(userid)-1] if type(userid) is str else None

# Establish Postgres DB connection (Yugabyte DB)
def psqldb_connect():
    connection = psycopg2.connect(
        dbname=anvil.secrets.get_secret('proddb_name'),
        host=anvil.secrets.get_secret('proddb_host'),
        port=anvil.secrets.get_secret('proddb_port'),
        user=anvil.secrets.get_secret('proddb_app_usr'),
        password=anvil.secrets.get_secret('proddb_app_pw'))
    return connection

# Return the DB FIN schema name
def schemafin():
  return "fin"

# Return the DB REFDATA schema name
def schemarefd():
  return "refdata"

# For debug print
def print_data_debug(message, debug_data):
    print('***[DEBUG]*** {}: {}'.format(message, debug_data))
