import anvil.secrets
import anvil.users
import anvil.server

# This is a server package. It runs on the Anvil server,
# rather than in the user's browser.

@anvil.server.callable
def get_user_data():
    """
    Get logged on user data.

    Returns:
        userid (string): User ID auto generated by Anvil when user was created, not reside in user table.
        email (string): User email address.
        role (string): User role.
    """
    from ..DataAccess import UserSettingDAModule
    
    user = anvil.users.get_user()
    if not user:
        return None

    userid = user.get_id()
    if type(userid) is str:
        userid = userid[userid.find(",")+1:len(userid)-1]
    else:
        raise Exception(f'Error in getting user ID, system terminating...')
    email = user['email']
    role = user['role']
    settings = UserSettingDAModule.select_settings()
    anvil.server.session['loglevel'] = settings.get_logging_level()
    return userid, email, role, settings

# Get user id (generated by Python)
def get_current_userid():
    userid = anvil.users.get_user().get_id()
    return int(userid[userid.find(",")+1:len(userid)-1]) if type(userid) is str else None

# Establish DB connection and determine which env DB to conntact to 
def db_connect():
    return psqldb_connect()
    
# Establish Postgres DB connection (Yugabyte DB)
def psqldb_connect():
    import psycopg2
    if anvil.app.environment.name in 'Dev':
        connection = psycopg2.connect(
            dbname=anvil.secrets.get_secret('devdb_name'),
            host=anvil.secrets.get_secret('devdb_host'),
            port=anvil.secrets.get_secret('devdb_port'),
            user=anvil.secrets.get_secret('devdb_app_usr'),
            password=anvil.secrets.get_secret('devdb_app_pw'))
    else:
        connection = psycopg2.connect(
            dbname=anvil.secrets.get_secret('proddb_name'),
            host=anvil.secrets.get_secret('proddb_host'),
            port=anvil.secrets.get_secret('proddb_port'),
            user=anvil.secrets.get_secret('proddb_app_usr'),
            password=anvil.secrets.get_secret('proddb_app_pw'))
    return connection
